valid_binary_config:
  - metadata: "meta"
    kind: "binary"
    plugins:
      - plugin_name: "binary_loopback::BinaryLoopback"

invalid_binary_config:
  - metadata: "meta"
    kind: "binary"
    plugins:
      - plugin_name: "binary_loopback::BinaryLoopback"
      - plugin_name: "not_found_plugin::NotFoundPlugin"

valid_json_config:
  - metadata: "meta"
    kind: "json"
    plugins:
      - plugin_name: "json_loopback::JsonLoopback"

invalid_json_config:
  - metadata: "meta"
    kind: "json"
    plugins:
      - plugin_name: "json_loopback::JsonLoopback"
      - plugin_name: "not_found_plugin::NotFoundPlugin"

valid_string_config:
  - metadata: "meta"
    kind: "string"
    plugins:
      - plugin_name: "string_loopback::StringLoopback"

invalid_string_config:
  - metadata: "meta"
    kind: "string"
    plugins:
      - plugin_name: "string_loopback::StringLoopback"
      - plugin_name: "not_found_plugin::NotFoundPlugin"
